### ISSUE TITLE
WPYscan

### ISSUE THREAD

**Issue by akaracing** [hmikihth/wpyscan#2]
hi, was wonder if you could help out, we have installed WPYSCAN on Mac OSX with python 2.7 and all the requirements listed, but on execution we get a number of messages, like
Alekss-iMac:wpyscan alekskruz$ python wprecon.py -u sputnik1.xyz 
Traceback (most recent call last):
  File "wprecon.py", line 12, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests/**init**.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/site-packages/requests/packages/**init**.py", line 29, in <module>
    import urllib3
  File "/usr/local/lib/python2.7/site-packages/urllib3/**init**.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 35, in <module>
    from .connection import (
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 15, in <module>
    from httplib import HTTPConnection as _HTTPConnection
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
Alekss-iMac:wpyscan alekskruz$ 

can you help? is there something missing

Thanks in advance

**Comment by hmikihth** [comment]
Something wrong with your python. 

Here there is an example of a similar error:
http://stackoverflow.com/questions/2989233/python-import-error-symbol-not-found-but-the-symbol-sis-s-is-not-present


Did you try with python3? The wpyscan has been ported to python3.

**Comment by hmikihth** [comment]
http://quabr.com/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder-trying-to-register-a-packa

**Comment by akaracing** [comment]
Hi, Thank you so much for your help, we have installed Python3 and ran the install setup.py.
on execution of wpyscan.py we get the following:

wpyscan -u interwebdefence.com -r
Traceback (most recent call last):
  File "/usr/local/bin/wpyscan", line 4, in <module>
    __import__('pkg_resources').run_script('wpyscan==0.1', 'wpyscan')
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/site-packages/wpyscan-0.1-py3.5.egg/EGG-INFO/scripts/wpyscan", line 12, in <module>
  File "/usr/local/lib/python3.5/site-packages/wpyscan-0.1-py3.5.egg/wpyscan/wprecon.py", line 10, in <module>
ImportError: No module named 'bs4'

we have these modules installes
pip freeze
beautifulsoup4==4.5.0
requests==2.10.0
urllib3==1.16

I thing we are very close, do you have any ideas what this maybe

regards
Aleks

**Comment by hmikihth** [comment]
The pip is python2.x, use pip3.

pip3 install bs4

**Comment by akaracing** [comment]
Hi,
Great i also did it for the other modules as well.

We now get this

wpyscan -u http://sputnik1.xyz -r

   -----------------------------------------
   | Imagine a fucking awesome title here  |
   | (like t-rex shooting lasers and stuff)|
   -----------------------------------------
   
[*] Themes
  [+] enfold
[*] Backup
  [+] wp-config.bak
  [+] wp-config.old
[*] Full path disclosure
  [+] http://sputnik1.xyz/wp-content/uploads/
  [+] http://sputnik1.xyz/wp-includes/
Alekss-iMac:bin alekskruz$ 


do you think it is working now, this was done on our test server, the out put is correct

many thanks for you kind help
regards
Aleks

**Comment by hmikihth** [comment]
Yes, that works. You are welcome :)

**Comment by akaracing** [comment]
can i give feed back on your awesome support?

**Comment by hmikihth** [comment]
If you want :)

The original developer is Ganapati, I have ported the wpyscan to Python3 and created a package for blackPanther OS. So if you have ideas or problems write us.

It is my LinkedIn profile:
https://www.linkedin.com/in/miklos-horvath-29753798
